//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GraphMolWrap {

public enum PropertyPickleOptions {
  NoProps = 0,
  MolProps = BOOST_BINARY(1),
  AtomProps = BOOST_BINARY(10),
  BondProps = BOOST_BINARY(100),
  QueryAtomData = BOOST_BINARY(
      10),
  PrivateProps = BOOST_BINARY(10000),
  ComputedProps = BOOST_BINARY(100000),
  AllProps = 0x7FFFFFFF
}

}
